fix env var loading

diff --git a/.github/workflows/terraform-deploy.yml b/.github/workflows/terraform-deploy.yml
--- a/.github/workflows/terraform-deploy.yml
+++ b/.github/workflows/terraform-deploy.yml
@@ -4,53 +4,101 @@ on:
   workflow_call:
   workflow_dispatch:
 
-env: 
-  TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
-  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
-
 jobs:
-  plan:
-    name: 'Terraform plan'
+  terraform-plan:
+    name: "Terraform Plan"
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v3
+      - name: Checkout Repository
+        uses: actions/checkout@v3
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
-      with:
-        terraform_version: 1.5.6
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.5.6
 
-    - name: Initialize Terraform
-      working-directory: terraform
-      run: terraform init
+      - name: Initialize Terraform
+        working-directory: terraform
+        run: terraform init
 
-    - name: Plan Terraform Deployment
-      working-directory: terraform
-      run: |
-        terraform plan
+      - name: Plan Terraform Deployment
+        working-directory: terraform
+        run: |
+          export exitcode=0
+          terraform plan \
+            -var="hcloud_token=${{ secrets.HCLOUD_TOKEN }}" \
+            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
+            -out main.tfplan || export exitcode=$?
 
-  apply:
-    name: 'Terraform apply'
-    needs: plan
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+          if [ $exitcode -eq 1 ]; then
+            echo "Error: Terraform plan failed"
+            exit 1
+          else
+            echo "Terraform plan was successful"
+            exit 0
+          fi
+
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: tfplan
+          path: ./terraform/main.tfplan       
+
+  terraform-apply:
+    needs: terraform-plan
+    name: "Terraform Apply"
     runs-on: ubuntu-latest
-    environment: terraform-apply
+    environment: dev
+    defaults:
+      run:
+        working-directory: ./terraform
 
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v3
+      - name: Checkout Repository
+        uses: actions/checkout@v3
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
-      with:
-        terraform_version: 1.5.6
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.5.6
 
-    - name: Initialize Terraform
-      working-directory: terraform
-      run: terraform init
+      - name: Terraform Init
+        id: init
+        run: terraform init
 
-    - name: Apply Terraform Configuration
-      working-directory: terraform
-      run: |
-        terraform apply -auto-approve
+      - name: Download Terraform Plan
+        uses: actions/download-artifact@v4
+        with:
+          name: tfplan
+          path: ./terraform
+
+      - name: Terraform Apply
+        run: terraform apply -auto-approve "./main.tfplan"
+
+  # apply:
+  #   name: 'Terraform apply'
+  #   needs: plan
+  #   runs-on: ubuntu-latest
+  #   environment: terraform-apply
+
+  #   steps:
+  #   - name: Checkout Repository
+  #     uses: actions/checkout@v3
+
+  #   - name: Setup Terraform
+  #     uses: hashicorp/setup-terraform@v2
+  #     with:
+  #       terraform_version: 1.5.6
+
+  #   - name: Initialize Terraform
+  #     working-directory: terraform
+  #     run: terraform init
+
+  #   - name: Apply Terraform Configuration
+  #     working-directory: terraform
+  #     run: |
+  #       terraform apply -auto-approve
+    
